In [91]:
import pandas as pd

In [92]:
df = pd.read_excel(r"C:\Users\sayan\OneDrive\Desktop\data analyst\pandas\Customer Call List.xlsx")
# df

In [93]:
df = df.drop_duplicates()

In [119]:
df = df.drop(columns = 'Not_Useful_Column')

In [95]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [96]:
df['Last_Name']

0         Baggins
1           Nadir
2          /White
3         Schrute
4            Snow
5         Swanson
6          Winger
7          Holmes
8             NaN
9          Parker
10         Gamgee
11      ...Potter
12         Draper
13          Knope
14    Flenderson_
15        Weasley
16          Scott
17           Kent
18         Braton
19      Skywalker
Name: Last_Name, dtype: object

In [97]:
df['Last_Name'] = df['Last_Name'].str.replace(r'[^A-Za-z]','', regex=True).str.strip()

In [98]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [99]:
df['Phone_Number']

0     123-545-5421
1     123/643/9775
2       7066950392
3     123-543-2345
4     876|678|3469
5     304-762-2467
6              NaN
7     876|678|3469
8              N/a
9     123-545-5421
10             NaN
11      7066950392
12    123-543-2345
13    876|678|3469
14    304-762-2467
15    123-545-5421
16    123/643/9775
17      7066950392
18             N/a
19    876|678|3469
Name: Phone_Number, dtype: object

In [100]:
df['Phone_Number'] = df['Phone_Number'].str.replace(r'[^A-Za-z0-9]','',regex=True).str.strip()

In [101]:
df['Phone_Number'].apply(lambda x: x[0:3] + '-' + x[3:6] + '-' + x[6:10])

TypeError: 'float' object is not subscriptable

In [102]:
df['Phone_Number'] = df['Phone_Number'].apply(lambda x: str(x))

In [103]:
df['Phone_Number'] = df['Phone_Number'].apply(lambda x: x[0:3] + '-' + x[3:6] + '-' + x[6:10])

In [122]:
df['Phone_Number'] = df['Phone_Number'].str.replace("nan--",'')

In [124]:
df['Phone_Number'] = df['Phone_Number'].str.replace("Na--",'')

In [53]:
df['Phone_Number']

0     123-545-5421
1     123-643-9775
2
3     123-543-2345
4     876-678-3469
5     304-762-2467
6
7     876-678-3469
8
9     123-545-5421
10
11
12    123-543-2345
13    876-678-3469
14    304-762-2467
15    123-545-5421
16    123-643-9775
17
18
19    876-678-3469
Name: Phone_Number, dtype: object

In [62]:
df[['Street_add','State','zip_code']]= df['Address'].str.split(',' ,n=2, expand=True)

In [104]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,False
2,1003,Walter,White,nan--,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,nan--,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,Na--,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,nan--,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,nan--,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,nan--,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,Na--,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [111]:
df['Paying Customer'] = df['Paying Customer'].str.replace('Yes','Y')

In [112]:
df['Paying Customer'] = df['Paying Customer'].str.replace('No','N')

In [107]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,No,True
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Yes,False
2,1003,Walter,White,nan--,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,True
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Yes,True
6,1007,Jeff,Winger,nan--,1209 South Street,N,No,False
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,Na--,123 Middle Earth,Y,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,No,True
10,1011,Samwise,Gamgee,nan--,"612 Shire Lane, Shire",Y,No,True
11,1012,Harry,Potter,nan--,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,False
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,No,False
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,False
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,No,False
17,1018,Clark,Kent,nan--,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,Na--,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,True

In [113]:
df['Do_Not_Contact'] = df['Do_Not_Contact'].str.replace('No','N')

In [114]:
df['Do_Not_Contact'] = df['Do_Not_Contact'].str.replace('Yes','Y')

In [115]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,True
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,False
2,1003,Walter,White,nan--,298 Drugs Driveway,N,,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,True
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,True
6,1007,Jeff,Winger,nan--,1209 South Street,N,N,False
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,False
8,1009,Gandalf,,Na--,123 Middle Earth,Y,,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,True
10,1011,Samwise,Gamgee,nan--,"612 Shire Lane, Shire",Y,N,True
11,1012,Harry,Potter,nan--,2394 Hogwarts Avenue,Y,,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,False
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,False
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,False
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,False
17,1018,Clark,Kent,nan--,3498 Super Lane,Y,,True
18,1019,Creed,Braton,Na--,,,Y,True
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,True

In [116]:
df = df.fillna('')

In [117]:
df = df.replace('N/a', '')

In [118]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,True
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,False
2,1003,Walter,White,nan--,298 Drugs Driveway,N,,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,True
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,True
6,1007,Jeff,Winger,nan--,1209 South Street,N,N,False
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,False
8,1009,Gandalf,,Na--,123 Middle Earth,Y,,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,True
10,1011,Samwise,Gamgee,nan--,"612 Shire Lane, Shire",Y,N,True
11,1012,Harry,Potter,nan--,2394 Hogwarts Avenue,Y,,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,False
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,False
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,False
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,False
17,1018,Clark,Kent,nan--,3498 Super Lane,Y,,True
18,1019,Creed,Braton,Na--,,,Y,True
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,True

In [120]:
 for x in df.index:
     if df.loc[x,'Do_Not_Contact'] == "Y":
         df.drop(x, inplace = True)

In [125]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N
2,1003,Walter,White,,298 Drugs Driveway,N,
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N
6,1007,Jeff,Winger,,1209 South Street,N,N
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N
8,1009,Gandalf,,,123 Middle Earth,Y,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N
17,1018,Clark,Kent,,3498 Super Lane,Y,
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N

In [131]:
for x in df.index:
    if df.loc[x,'Phone_Number'] == '':
        df.drop(x,inplace = True)

In [132]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N

In [142]:

df = df.reset_index(drop=True)

In [143]:
df

,index,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N
1,4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N
2,7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N
3,9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N
4,12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N
5,13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N
6,14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N
7,15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N
8,16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N
9,19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N

In [147]:
df.columns

Index(['index', 'CustomerID', 'First_Name', 'Last_Name', 'Phone_Number',
       'Address', 'Paying Customer', 'Do_Not_Contact'],
      dtype='object')

In [148]:
df.drop(columns='index')

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N
1,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N
2,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N
3,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N
4,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N
5,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N
6,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N
7,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N
8,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N
9,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N